"""fixes

Revision ID: 27a645220713
Revises: 4d051e6f7b37
Create Date: 2024-02-23 12:27:39.977470

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "27a645220713"
down_revision = "4d051e6f7b37"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.alter_column(
            "kontonummer",
            existing_type=mysql.VARCHAR(length=16),
            type_=sa.String(length=20),
            existing_nullable=False,
        )

    with op.batch_alter_table("customer", schema=None) as batch_op:
        batch_op.alter_column(
            "personnummer",
            existing_type=mysql.VARCHAR(length=12),
            type_=sa.String(length=13),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("customer", schema=None) as batch_op:
        batch_op.alter_column(
            "personnummer",
            existing_type=sa.String(length=13),
            type_=mysql.VARCHAR(length=12),
            existing_nullable=False,
        )

    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.alter_column(
            "kontonummer",
            existing_type=sa.String(length=20),
            type_=mysql.VARCHAR(length=16),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
