"""long ints to string

Revision ID: 3339d3212854
Revises: d89577ec95a4
Create Date: 2024-02-13 17:32:15.497629

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "3339d3212854"
down_revision = "d89577ec95a4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.alter_column(
            "kontonummer",
            existing_type=mysql.INTEGER(),
            type_=sa.String(length=12),
            existing_nullable=False,
        )

    with op.batch_alter_table("customer", schema=None) as batch_op:
        batch_op.alter_column(
            "kundnummer",
            existing_type=mysql.INTEGER(),
            type_=sa.String(length=12),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "personnummer",
            existing_type=mysql.INTEGER(),
            type_=sa.String(length=10),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("customer", schema=None) as batch_op:
        batch_op.alter_column(
            "personnummer",
            existing_type=sa.String(length=10),
            type_=mysql.INTEGER(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "kundnummer",
            existing_type=sa.String(length=12),
            type_=mysql.INTEGER(),
            existing_nullable=False,
        )

    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.alter_column(
            "kontonummer",
            existing_type=sa.String(length=12),
            type_=mysql.INTEGER(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
