"""fixes

Revision ID: 4d051e6f7b37
Revises: 5f1d2bfebfd1
Create Date: 2024-02-23 12:25:02.083665

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "4d051e6f7b37"
down_revision = "5f1d2bfebfd1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.alter_column(
            "kontonummer",
            existing_type=mysql.VARCHAR(length=12),
            type_=sa.String(length=16),
            existing_nullable=False,
        )

    with op.batch_alter_table("customer", schema=None) as batch_op:
        batch_op.alter_column(
            "personnummer",
            existing_type=mysql.VARCHAR(length=10),
            type_=sa.String(length=12),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("customer", schema=None) as batch_op:
        batch_op.alter_column(
            "personnummer",
            existing_type=sa.String(length=12),
            type_=mysql.VARCHAR(length=10),
            existing_nullable=False,
        )

    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.alter_column(
            "kontonummer",
            existing_type=sa.String(length=16),
            type_=mysql.VARCHAR(length=12),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
