"""transaction model upgrade

Revision ID: 5f1d2bfebfd1
Revises: 7bdaf6945419
Create Date: 2024-02-21 21:39:58.778766

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f1d2bfebfd1'
down_revision = '7bdaf6945419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=6), nullable=False))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=False))
        batch_op.drop_column('typ')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('typ', mysql.VARCHAR(length=6), nullable=False))
        batch_op.drop_column('timestamp')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
