"""address for kund

Revision ID: 7bdaf6945419
Revises: e3ad815bcf76
Create Date: 2024-02-20 13:21:24.141719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7bdaf6945419"
down_revision = "e3ad815bcf76"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("customer", schema=None) as batch_op:
        batch_op.add_column(sa.Column("adress", sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("customer", schema=None) as batch_op:
        batch_op.drop_column("adress")

    # ### end Alembic commands ###
