"""test

Revision ID: d89577ec95a4
Revises: 
Create Date: 2024-02-13 17:10:02.201369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd89577ec95a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kontonummer', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['kontonummer'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('kontonummer')

    # ### end Alembic commands ###
