"""kundnummer is no more

Revision ID: e3ad815bcf76
Revises: e6e90d7c0406
Create Date: 2024-02-19 09:08:15.901362

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "e3ad815bcf76"
down_revision = "e6e90d7c0406"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("customer", schema=None) as batch_op:
        batch_op.drop_index("kundnummer")
        batch_op.drop_column("kundnummer")

    with op.batch_alter_table("super_user", schema=None) as batch_op:
        batch_op.alter_column(
            "password",
            existing_type=mysql.VARCHAR(length=80),
            type_=sa.String(length=64),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("super_user", schema=None) as batch_op:
        batch_op.alter_column(
            "password",
            existing_type=sa.String(length=64),
            type_=mysql.VARCHAR(length=80),
            existing_nullable=False,
        )

    with op.batch_alter_table("customer", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("kundnummer", mysql.VARCHAR(length=12), nullable=False)
        )
        batch_op.create_index("kundnummer", ["kundnummer"], unique=True)

    # ### end Alembic commands ###
