"""fixed city type being int

Revision ID: fd6312bd542f
Revises: 526b49207408
Create Date: 2024-01-10 16:54:09.096722

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fd6312bd542f'
down_revision = '526b49207408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('city',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('city',
               existing_type=sa.String(length=80),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
